# Generated by Django 3.1.1 on 2020-09-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='technology_type',
            field=models.CharField(choices=[('DV', 'DevOps'), ('SYS', 'Systems'), ('D', 'Develop'), ('DB', 'Database'), ('T', 'Testing')], default=str, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
